name: new1
description: A new Flutter project.

publish_to: 'none'

#
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/QR-code.png
    - assets/flash.png
    - assets/image.png
    - assets/qo.png


  uses-material-design: true


